name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

permissions:
  contents: write
  pages: write 
  id-token: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate pacman.svg
        uses: Platane/snk@v3
        with:
          github_user_name: sheemasyed02
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?palette=github-dark&color_snake=#FF9554&color_dots=#7536B2,#9243DD,#BC52FF,#D280FF,#64EAE2
            
      - name: Upload artifacts (for debugging)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pacman-svg-files
          path: dist/
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist/
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
